[program:storybook]
command=bash -c "cd /var/www/html/storybook && npm run dev"
directory=/var/www/html/storybook
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/tmp/storybook.err.log
stdout_logfile=/var/tmp/storybook.out.log
